security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        public:
            pattern: ^/api/(register|forgot-password|reset-password|docs|contexts)
            stateless: true
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    # Auth et accès publics
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts, roles: PUBLIC_ACCESS }
        - { path: ^/api/events, roles: PUBLIC_ACCESS, methods: [GET] }
        

    # Logs : réservés aux admins
        - { path: ^/api/logs, roles: ROLE_ADMIN }

    # Accès aux utilisateurs connectés    
        - { path: ^/api/reservations, roles: ROLE_USER }
        - { path: ^/api/enrollments, roles: ROLE_USER }
        - { path: ^/api/me, roles: ROLE_USER }

    # Fallback général pour toutes les autres routes protégées
        - { path: ^/api/(?!docs|contexts|login).*, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
