services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            # - '../src/Entity/'  # OK ici si tu ne veux pas que les entités soient autowirées
            - '../src/Kernel.php'

    App\Controller\EmailVerificationController:
        tags: ['controller.service_arguments']

    App\Controller\AuthController:
        public: true
        tags: ['controller.service_arguments']

    App\Controller\InscriptionAtelierController:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $mailer: '@mailer.mailer'
            $twig: '@twig'
            $security: '@Symfony\Bundle\SecurityBundle\Security'
        tags: ['controller.service_arguments']
        public: true
